/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Mobile.API.Automation;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
	
	
   
}
