///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package com.sentieo.utils;
//
//import java.io.IOException;
//
//import org.codehaus.jackson.annotate.JsonMethod;
//import org.codehaus.jackson.annotate.JsonAutoDetect.Visibility;
//import org.codehaus.jackson.map.DeserializationConfig;
//import org.codehaus.jackson.map.ObjectMapper;
//import org.codehaus.jackson.map.SerializationConfig;
//import org.testng.annotations.DataProvider;
//
//
//public class JSONUtils {
//
//	
//	private ObjectMapper objectMapper;
//	
//	
//	
//	public JSONUtils() {
//		// TODO Auto-generated constructor stub
//		objectMapper = new ObjectMapper();
//		objectMapper.setVisibility(JsonMethod.FIELD, Visibility.ANY).setVisibility(JsonMethod.SETTER, Visibility.NONE)
//				.setVisibility(JsonMethod.GETTER, Visibility.NONE).setVisibility(JsonMethod.IS_GETTER, Visibility.NONE)
//				.configure(DeserializationConfig.Feature.FAIL_ON_UNKNOWN_PROPERTIES, false)
//				.configure(SerializationConfig.Feature.AUTO_DETECT_GETTERS, false)
//				.configure(SerializationConfig.Feature.AUTO_DETECT_IS_GETTERS, false);
//		
//	}
//	
//	@DataProvider(name = "tickerdataprovider")
//    Object [][] getTickerName() throws IOException
//    {
//        String path = System.getProperty("user.dir")+ "/src/test/resources/Data_provider.xlsx";
//		
//       // String path ="/Users/malikajain/eclipse-workspace/Mobile API Automation/src/test/resources/login_credentials.xlsx";
//        
//        int rowCount = XLUtils.getRowCount(path,"Sheet1");
//        int colCount = XLUtils.getCellCount(path,"Sheet1",0);
//        Object tickerData[][]= new Object[rowCount][colCount];
//        
//        for(int i=1; i<=rowCount; i++)
//        {
//            for(int j=0; j<colCount; j++)
//            {
//            	tickerData[i-1][j] = XLUtils.getCellData(path,"Sheet1", i, j);
//                System.out.println(tickerData[i-1][j]);
//            }
//        }
//        return tickerData;
//    }
//	
//	
//	public String toJson(Object object) {
//		try {
//			return objectMapper.writeValueAsString(object);
//		} catch (Exception e) {
//			throw new RuntimeException("Json conversion failure - Received object is not in valid format - " + object,
//					e);
//		}
//	}
//	
//	
//	
//}
